language: node_js
node_js:
  - "8"
deploy:
  provider: pages
  local-dir: ./hexo/public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master